"""
backend.api.v1.reports — Report generation and download endpoints.

POST /reports/generate      — generate session report (JSON + PDF)
GET  /reports               — list generated reports
GET  /reports/{id}/download — download report file (JSON or PDF)
GET  /reports/{id}          — get report metadata
DELETE /reports/{id}        — delete report
"""

from __future__ import annotations

import json
import time
import uuid
from pathlib import Path
from typing import Annotated

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Path as FPath, Query
from fastapi.responses import FileResponse
from pydantic import BaseModel
from sqlmodel import Session, select

from backend.config import get_settings
from backend.database import get_session

router = APIRouter(prefix="/reports", tags=["reports"])

settings = get_settings()

# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------

class ReportRequest(BaseModel):
    session_id: str | None = None
    dataset_id: int | None = None
    run_id: int | None = None
    include_scientific_caveats: bool = True
    include_calibration: bool = True
    format: str = "json"  # "json" | "pdf" | "csv"
    title: str = "Trichome Analysis Report"


class ReportMeta(BaseModel):
    id: str
    title: str
    format: str
    created_at: str
    file_path: str | None
    file_size_bytes: int | None
    status: str


# ---------------------------------------------------------------------------
# In-memory report store (replace with DB in production)
# ---------------------------------------------------------------------------

_REPORTS: dict[str, dict] = {}


# ---------------------------------------------------------------------------
# Report generator
# ---------------------------------------------------------------------------

def _generate_json_report(request: ReportRequest, report_id: str) -> Path:
    """Generate a JSON report and save to disk. Returns output path."""
    output_dir = Path(settings.data_dir) / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{report_id}.json"

    report = {
        "report_id": report_id,
        "title": request.title,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "format_version": "1.0",
        "session_id": request.session_id,
        "dataset_id": request.dataset_id,
        "run_id": request.run_id,
        "sections": {
            "summary": {
                "description": "Trichome analysis summary",
                "note": "This report was generated by the Trichome Analysis System.",
            },
            "scientific_caveats": (
                {
                    "maturity_analysis": (
                        "Trichome maturity stage (clear/cloudy/amber) reflects observable "
                        "optical properties. No inference about cannabinoid content (THC, "
                        "CBD, CBN) can be made from visual appearance alone. See: "
                        "ElSohly & Slade (2005), Elzinga et al. (2015)."
                    ),
                    "thc_proxy_claim": "NOT SUPPORTED by scientific literature.",
                    "supported_analyses": [
                        "Trichome density (counts/mm²)",
                        "Morphological type classification",
                        "Color distribution analysis",
                        "Oxidative degradation detection",
                    ],
                }
                if request.include_scientific_caveats
                else {}
            ),
            "methodology": {
                "detection": "YOLO11 anchor-free detection with WBF ensemble merging",
                "maturity": "HSV/LAB color feature analysis with VLM assistance",
                "calibration": "Stage micrometer-based px→µm calibration",
                "references": [
                    "Jocher et al. (2023). Ultralytics YOLO.",
                    "Solovyev et al. (2021). Weighted Boxes Fusion. IVC 107:104117.",
                    "Guo et al. (2017). On Calibration of Modern Neural Networks. ICML.",
                ],
            },
        },
    }

    output_path.write_text(json.dumps(report, indent=2))
    return output_path


def _generate_pdf_report(request: ReportRequest, report_id: str) -> Path:
    """Generate a PDF report using ReportLab. Returns output path."""
    output_dir = Path(settings.data_dir) / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{report_id}.pdf"

    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm
        from reportlab.platypus import (
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )

        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            rightMargin=20 * mm,
            leftMargin=20 * mm,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
        )

        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = ParagraphStyle(
            "Title",
            parent=styles["Title"],
            fontSize=18,
            spaceAfter=6 * mm,
        )
        story.append(Paragraph(request.title, title_style))
        story.append(
            Paragraph(
                f"Report ID: {report_id} | Generated: {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}",
                styles["Normal"],
            )
        )
        story.append(Spacer(1, 8 * mm))

        # Scientific caveat box
        if request.include_scientific_caveats:
            story.append(Paragraph("⚠ Scientific Limitations", styles["Heading2"]))
            story.append(
                Paragraph(
                    "Trichome maturity stage (clear/cloudy/amber) reflects observable optical "
                    "properties only. No inference about cannabinoid content (THC, CBD, CBN) "
                    "can be made from visual appearance. This system measures trichome density, "
                    "morphological type, and color distribution — not cannabinoid concentrations.",
                    styles["Normal"],
                )
            )
            story.append(Spacer(1, 6 * mm))

        # Methodology section
        story.append(Paragraph("Methodology", styles["Heading2"]))
        methodology_data = [
            ["Component", "Method"],
            ["Detection", "YOLO11 anchor-free + WBF merging"],
            ["Maturity", "HSV/LAB color features + VLM verification"],
            ["Segmentation", "SAM2-tiny instance segmentation"],
            ["Calibration", "Stage micrometer px→µm"],
        ]
        table = Table(methodology_data, colWidths=[60 * mm, 100 * mm])
        table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f8f9fa"), colors.white]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ])
        )
        story.append(table)

        doc.build(story)

    except ImportError:
        # ReportLab not installed — write placeholder
        output_path.write_bytes(
            b"%PDF-1.4\n%% ReportLab not installed. Install: pip install reportlab\n"
        )

    return output_path


# ---------------------------------------------------------------------------
# Background task
# ---------------------------------------------------------------------------

def _run_report_generation(report_id: str, request: ReportRequest) -> None:
    """Background task: generate report and update status."""
    try:
        _REPORTS[report_id]["status"] = "generating"

        if request.format == "pdf":
            path = _generate_pdf_report(request, report_id)
        elif request.format == "csv":
            # CSV: just dump JSON for now (proper CSV export in analytics/export/csv_exporter.py)
            path = _generate_json_report(request, report_id)
        else:
            path = _generate_json_report(request, report_id)

        _REPORTS[report_id].update({
            "status": "ready",
            "file_path": str(path),
            "file_size_bytes": path.stat().st_size if path.exists() else 0,
        })

    except Exception as exc:
        _REPORTS[report_id]["status"] = f"error: {exc}"


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@router.post("/generate", status_code=202)
async def generate_report(
    request: ReportRequest,
    background_tasks: BackgroundTasks,
) -> dict:
    """
    Queue report generation as a background task.

    Returns report_id immediately. Poll GET /reports/{id} to check status.
    Download via GET /reports/{id}/download when status = 'ready'.
    """
    report_id = str(uuid.uuid4())[:8]
    _REPORTS[report_id] = {
        "id": report_id,
        "title": request.title,
        "format": request.format,
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "status": "queued",
        "file_path": None,
        "file_size_bytes": None,
    }

    background_tasks.add_task(_run_report_generation, report_id, request)

    return {
        "report_id": report_id,
        "status": "queued",
        "message": "Report generation started",
        "poll_url": f"/api/v1/reports/{report_id}",
    }


@router.get("", response_model=list[ReportMeta])
def list_reports() -> list[ReportMeta]:
    """List all generated reports."""
    return [ReportMeta(**r) for r in _REPORTS.values()]


@router.get("/{report_id}", response_model=ReportMeta)
def get_report(report_id: Annotated[str, FPath()]) -> ReportMeta:
    """Get report metadata and generation status."""
    if report_id not in _REPORTS:
        raise HTTPException(status_code=404, detail=f"Report {report_id} not found")
    return ReportMeta(**_REPORTS[report_id])


@router.get("/{report_id}/download")
def download_report(report_id: Annotated[str, FPath()]) -> FileResponse:
    """Download generated report file (JSON or PDF)."""
    if report_id not in _REPORTS:
        raise HTTPException(status_code=404, detail=f"Report {report_id} not found")

    meta = _REPORTS[report_id]
    if meta["status"] != "ready":
        raise HTTPException(
            status_code=409,
            detail=f"Report not ready yet (status: {meta['status']})",
        )

    path = meta.get("file_path")
    if not path or not Path(path).exists():
        raise HTTPException(status_code=404, detail="Report file not found on disk")

    fmt = meta.get("format", "json")
    media_types = {
        "json": "application/json",
        "pdf": "application/pdf",
        "csv": "text/csv",
    }

    return FileResponse(
        path=path,
        media_type=media_types.get(fmt, "application/octet-stream"),
        filename=f"trichome_report_{report_id}.{fmt}",
    )


@router.delete("/{report_id}")
def delete_report(report_id: Annotated[str, FPath()]) -> dict:
    """Delete report metadata and optionally the file."""
    if report_id not in _REPORTS:
        raise HTTPException(status_code=404, detail=f"Report {report_id} not found")

    meta = _REPORTS.pop(report_id)
    path = meta.get("file_path")
    if path:
        try:
            Path(path).unlink(missing_ok=True)
        except Exception:
            pass

    return {"message": f"Report {report_id} deleted"}
