"""
backend.api.v1.vlm_ensemble — VLM multi-provider ensemble inference endpoints.

Endpoints:
    POST /vlm/ensemble/label          — Run inference across multiple providers, return consensus
    GET  /vlm/prompts                 — List all available prompt templates
    GET  /vlm/prompts/{name}          — Get a specific prompt template by name
    POST /vlm/prompts/validate        — Validate a custom prompt JSON against schema

DESIGN:
    - All provider calls are executed concurrently via asyncio.gather + run_in_executor
    - Local providers (moondream, qwen2vl, florence2) acquire the GPU semaphore before inference
    - Remote providers (openai, anthropic, google, together, groq, huggingface) skip GPU semaphore
    - Missing or invalid API keys → provider skipped with error, not HTTP 500
    - Consensus is majority-vote on maturity_stage; agreement score = fraction matching majority

SCIENTIFIC CAVEAT:
    Ensemble agreement increases pseudo-label confidence but does NOT replace human review.
    All VLM outputs remain AnnotationSource.VLM_AUTO. HITL gate is enforced upstream.
"""

from __future__ import annotations

import asyncio
import base64
import time
from collections import Counter
from functools import partial
from typing import Any

import numpy as np
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field, field_validator

from shared.logging.logger import get_logger
from vlm_labeling.provider_registry import get_registry  # noqa: E402 — imported for mock-patchability

logger = get_logger(__name__)

router = APIRouter(prefix="/vlm", tags=["vlm-ensemble"])

# ── Provider classification ────────────────────────────────────────────────────

_LOCAL_PROVIDERS: frozenset[str] = frozenset({"moondream", "qwen2vl", "florence2"})
_REMOTE_PROVIDERS: frozenset[str] = frozenset(
    {"openai", "anthropic", "google", "together", "groq", "huggingface"}
)

_VALID_TASKS: frozenset[str] = frozenset({"maturity", "morphology", "quality_screen"})

# Scientific caveat template — shown in every ensemble response.
_SCIENTIFIC_CAVEAT = (
    "VLM ensemble outputs are pseudo-labels generated by automated vision-language models. "
    "They reflect optical observations of trichome morphology only. "
    "Cannabinoid content (THC/CBD) cannot be determined from microscopy images. "
    "These labels MUST be reviewed and approved by a qualified human annotator "
    "before being used for model training or scientific reporting."
)


# ── Request / Response Schemas ─────────────────────────────────────────────────

class EnsembleLabelRequest(BaseModel):
    image_base64: str = Field(description="Base64-encoded image (JPEG or PNG)")
    providers: list[str] = Field(
        description="List of provider IDs to query, e.g. ['groq', 'together', 'moondream']"
    )
    model_overrides: dict[str, str] = Field(
        default_factory=dict,
        description="Optional per-provider model overrides, e.g. {'together': 'Qwen/Qwen2-VL-72B-Instruct'}",
    )
    task: str = Field(
        description="Inference task: 'maturity' | 'morphology' | 'quality_screen'"
    )
    prompt_override: dict[str, str] | None = Field(
        default=None,
        description="Optional custom prompt with 'system' and 'user' fields",
    )

    @field_validator("providers")
    @classmethod
    def providers_not_empty(cls, v: list[str]) -> list[str]:
        if not v:
            raise ValueError("providers list must not be empty")
        return v

    @field_validator("task")
    @classmethod
    def task_must_be_valid(cls, v: str) -> str:
        if v not in _VALID_TASKS:
            raise ValueError(
                f"task must be one of {sorted(_VALID_TASKS)}, got '{v}'"
            )
        return v


class ProviderResult(BaseModel):
    provider_id: str
    model: str | None
    maturity_stage: str | None = None
    dominant_type: str | None = None
    overall_quality: str | None = None
    confidence: float
    elapsed_ms: float
    raw_response: dict[str, Any] | None = None
    error: str | None = None


class ConsensusResult(BaseModel):
    maturity_stage: str | None = None
    dominant_type: str | None = None
    overall_quality: str | None = None
    agreement_score: float
    agreement_level: str  # "high" >= 0.8, "medium" >= 0.6, "low" < 0.6
    participating_providers: list[str]
    dissenting_providers: list[str]


class EnsembleLabelResponse(BaseModel):
    results: list[ProviderResult]
    consensus: ConsensusResult
    scientific_caveat: str


class PromptTemplateResponse(BaseModel):
    name: str
    system_prompt: str
    user_prompt_template: str
    output_schema: dict[str, Any]
    model_compatibility: list[str]
    notes: str


class PromptValidationRequest(BaseModel):
    system: str = Field(description="System prompt text")
    user: str = Field(description="User prompt template text")
    output_schema: dict[str, Any] | None = Field(
        default=None,
        description="Optional JSON Schema object the model output should conform to",
    )


class PromptValidationResponse(BaseModel):
    valid: bool
    errors: list[str]


# ── Internal helpers ───────────────────────────────────────────────────────────

def _decode_image(image_base64: str) -> np.ndarray:
    """Decode a base64 image string to an RGB numpy array."""
    import cv2

    try:
        raw_bytes = base64.b64decode(image_base64)
    except Exception as exc:
        raise HTTPException(
            status_code=422,
            detail=f"Invalid base64 encoding: {exc}",
        )

    arr = np.frombuffer(raw_bytes, dtype=np.uint8)
    img_bgr = cv2.imdecode(arr, cv2.IMREAD_COLOR)
    if img_bgr is None:
        raise HTTPException(
            status_code=422,
            detail="Cannot decode image — ensure it is a valid JPEG or PNG encoded as base64.",
        )
    return cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)


def _agreement_level(score: float) -> str:
    if score >= 0.8:
        return "high"
    if score >= 0.6:
        return "medium"
    return "low"


def _compute_consensus(
    results: list[ProviderResult],
    task: str,
) -> ConsensusResult:
    """
    Compute majority-vote consensus from successful provider results.

    Agreement score = (# providers matching majority label) / (# participating providers).
    Tie-breaking: alphabetically first label among tied candidates wins.
    """
    # Only use results that produced a label (no error, is_valid)
    label_key = _task_label_key(task)

    valid_results = [r for r in results if r.error is None]
    if not valid_results:
        return ConsensusResult(
            agreement_score=0.0,
            agreement_level="low",
            participating_providers=[],
            dissenting_providers=[r.provider_id for r in results],
        )

    labels: list[str] = []
    for r in valid_results:
        label = getattr(r, label_key, None)
        if label is not None:
            labels.append(label)

    if not labels:
        return ConsensusResult(
            agreement_score=0.0,
            agreement_level="low",
            participating_providers=[r.provider_id for r in valid_results],
            dissenting_providers=[],
        )

    # Majority vote with alphabetic tie-breaking
    counts = Counter(labels)
    max_count = max(counts.values())
    # Among all labels with max_count, pick alphabetically first for determinism
    majority_label = min(
        (label for label, cnt in counts.items() if cnt == max_count)
    )

    agreement_score = max_count / len(valid_results)
    agreement_level = _agreement_level(agreement_score)

    participating = [r.provider_id for r in valid_results]
    dissenting = [
        r.provider_id
        for r in valid_results
        if getattr(r, label_key, None) != majority_label
    ]

    kwargs: dict[str, Any] = {
        "agreement_score": round(agreement_score, 4),
        "agreement_level": agreement_level,
        "participating_providers": participating,
        "dissenting_providers": dissenting,
    }
    kwargs[label_key] = majority_label
    return ConsensusResult(**kwargs)


def _task_label_key(task: str) -> str:
    """Return the ProviderResult field name that holds the label for a given task."""
    if task == "maturity":
        return "maturity_stage"
    if task == "morphology":
        return "dominant_type"
    if task == "quality_screen":
        return "overall_quality"
    return "maturity_stage"


def _extract_label_from_response(
    parsed: dict[str, Any] | None,
    task: str,
) -> str | None:
    """Extract the primary label field from a parsed VLM response."""
    if parsed is None:
        return None
    if task == "maturity":
        return parsed.get("maturity_stage")
    if task == "morphology":
        return parsed.get("dominant_type")
    if task == "quality_screen":
        return parsed.get("overall_quality")
    return None


def _call_provider_sync(
    provider_id: str,
    model_override: str | None,
    image: np.ndarray,
    task: str,
) -> ProviderResult:
    """
    Synchronous provider call — runs inside a thread via run_in_executor.

    Local providers acquire the GPU semaphore via a nested event loop.
    This is intentional: the GPU semaphore is an asyncio.Semaphore and must be
    managed from an async context even when called from a thread.

    Returns a ProviderResult (never raises).
    """
    registry = get_registry()
    t0 = time.perf_counter()

    # ── Instantiate provider ──────────────────────────────────────────────
    try:
        provider = registry.get(provider_id, model=model_override)
    except ValueError as exc:
        # Missing API key or unknown provider
        err_msg = str(exc)
        if "API key" in err_msg or "required" in err_msg.lower():
            err_msg = "API key not configured"
        return ProviderResult(
            provider_id=provider_id,
            model=model_override,
            confidence=0.0,
            elapsed_ms=round((time.perf_counter() - t0) * 1000, 1),
            error=err_msg,
        )
    except Exception as exc:
        return ProviderResult(
            provider_id=provider_id,
            model=model_override,
            confidence=0.0,
            elapsed_ms=round((time.perf_counter() - t0) * 1000, 1),
            error=f"Provider initialization failed: {exc}",
        )

    # ── Dispatch task ─────────────────────────────────────────────────────
    try:
        if task == "maturity":
            response = provider.label_maturity(image)
        elif task == "morphology":
            response = provider.label_morphology(image)
        elif task == "quality_screen":
            response = provider.assess_quality(image)
        else:
            raise ValueError(f"Unknown task: {task}")
    except Exception as exc:
        return ProviderResult(
            provider_id=provider_id,
            model=getattr(provider, "_model", None) or provider.info.default_model,
            confidence=0.0,
            elapsed_ms=round((time.perf_counter() - t0) * 1000, 1),
            error=str(exc),
        )

    elapsed_ms = round((time.perf_counter() - t0) * 1000, 1)
    parsed = response.parsed_response

    label_key = _task_label_key(task)
    label_value = _extract_label_from_response(parsed, task)

    result_kwargs: dict[str, Any] = {
        "provider_id": provider_id,
        "model": response.model_id or provider.info.default_model,
        "confidence": response.confidence,
        "elapsed_ms": elapsed_ms,
        "raw_response": parsed,
        "error": response.error if not response.is_valid else None,
    }
    result_kwargs[label_key] = label_value

    return ProviderResult(**result_kwargs)


async def _call_provider_async(
    provider_id: str,
    model_override: str | None,
    image: np.ndarray,
    task: str,
    loop: asyncio.AbstractEventLoop,
) -> ProviderResult:
    """
    Async wrapper for a single provider call.

    - Remote providers: runs directly in executor (no GPU semaphore).
    - Local providers: acquires GPU semaphore before submitting to executor.
    """
    is_local = provider_id in _LOCAL_PROVIDERS
    fn = partial(_call_provider_sync, provider_id, model_override, image, task)

    if is_local:
        from backend.dependencies.gpu import acquire_gpu_slot
        async with acquire_gpu_slot():
            return await loop.run_in_executor(None, fn)
    else:
        return await loop.run_in_executor(None, fn)


# ── Endpoints ──────────────────────────────────────────────────────────────────

@router.post("/ensemble/label", response_model=EnsembleLabelResponse)
async def ensemble_label(req: EnsembleLabelRequest) -> EnsembleLabelResponse:
    """
    Run VLM inference across multiple providers in parallel and return consensus.

    Providers are queried concurrently via asyncio.gather.
    Local providers (moondream, qwen2vl, florence2) acquire the shared GPU semaphore
    serially — only one local model can run at a time on the RTX 4060.

    Missing API keys cause the provider to be skipped (error field set), not HTTP 500.
    The consensus is a majority vote across all providers that returned a valid label.
    """
    image = _decode_image(req.image_base64)
    loop = asyncio.get_event_loop()

    tasks = []
    for provider_id in req.providers:
        model_override = req.model_overrides.get(provider_id)
        tasks.append(
            _call_provider_async(provider_id, model_override, image, req.task, loop)
        )

    results: list[ProviderResult] = await asyncio.gather(*tasks, return_exceptions=False)

    consensus = _compute_consensus(list(results), req.task)

    logger.info(
        "VLM ensemble inference complete",
        task=req.task,
        num_providers=len(req.providers),
        consensus_label=consensus.maturity_stage or consensus.dominant_type or consensus.overall_quality,
        agreement_score=consensus.agreement_score,
        agreement_level=consensus.agreement_level,
    )

    return EnsembleLabelResponse(
        results=list(results),
        consensus=consensus,
        scientific_caveat=_SCIENTIFIC_CAVEAT,
    )


@router.get("/prompts", response_model=list[PromptTemplateResponse])
async def list_prompt_templates() -> list[PromptTemplateResponse]:
    """
    List all available VLM prompt templates.

    Returns names, system/user prompts, output schemas, and model compatibility notes
    for all registered trichome analysis prompt templates.
    """
    from vlm_labeling.prompts.trichome_prompts import PROMPT_REGISTRY

    return [
        PromptTemplateResponse(
            name=tmpl.name,
            system_prompt=tmpl.system_prompt,
            user_prompt_template=tmpl.user_prompt_template,
            output_schema=tmpl.output_schema,
            model_compatibility=tmpl.model_compatibility,
            notes=tmpl.notes,
        )
        for tmpl in PROMPT_REGISTRY.values()
    ]


@router.get("/prompts/{name}", response_model=PromptTemplateResponse)
async def get_prompt_template(name: str) -> PromptTemplateResponse:
    """
    Get a specific VLM prompt template by name.

    Returns the full template including system prompt, user prompt template,
    expected output JSON schema, and compatible model list.
    """
    from vlm_labeling.prompts.trichome_prompts import PROMPT_REGISTRY

    tmpl = PROMPT_REGISTRY.get(name)
    if tmpl is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Prompt template '{name}' not found. "
                f"Available: {sorted(PROMPT_REGISTRY.keys())}"
            ),
        )

    return PromptTemplateResponse(
        name=tmpl.name,
        system_prompt=tmpl.system_prompt,
        user_prompt_template=tmpl.user_prompt_template,
        output_schema=tmpl.output_schema,
        model_compatibility=tmpl.model_compatibility,
        notes=tmpl.notes,
    )


@router.post("/prompts/validate", response_model=PromptValidationResponse)
async def validate_prompt(req: PromptValidationRequest) -> PromptValidationResponse:
    """
    Validate a custom prompt object against basic structural requirements.

    Checks:
    - system and user fields are non-empty strings
    - output_schema (if provided) is a valid JSON Schema object with 'properties' or 'required'
    - No forbidden patterns (e.g., THC/cannabinoid content claims)
    """
    errors: list[str] = []

    if not req.system.strip():
        errors.append("'system' prompt must not be empty")

    if not req.user.strip():
        errors.append("'user' prompt must not be empty")

    if len(req.system) > 4096:
        errors.append("'system' prompt exceeds maximum length of 4096 characters")

    if len(req.user) > 8192:
        errors.append("'user' prompt exceeds maximum length of 8192 characters")

    # Warn about forbidden scientific claims
    _FORBIDDEN_PATTERNS = [
        ("THC content", "THC content cannot be determined from microscopy images"),
        ("CBD content", "CBD content cannot be determined from microscopy images"),
        ("potency", "Cannabinoid potency claims are not scientifically valid in this context"),
    ]
    for pattern, message in _FORBIDDEN_PATTERNS:
        if pattern.lower() in req.user.lower() or pattern.lower() in req.system.lower():
            errors.append(f"Forbidden claim detected: {message}")

    if req.output_schema is not None:
        if not isinstance(req.output_schema, dict):
            errors.append("'output_schema' must be a JSON object (dict)")
        elif not any(k in req.output_schema for k in ("properties", "required", "type")):
            errors.append(
                "'output_schema' should contain at least one of: 'properties', 'required', 'type'"
            )

    return PromptValidationResponse(valid=len(errors) == 0, errors=errors)
